# Generated by Django 4.2.3 on 2024-09-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_screencaptures_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screencaptures',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
