# Generated by Django 4.2.3 on 2024-09-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_screencaptures_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='logs',
            name='end_time',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='logs',
            name='start_time',
            field=models.CharField(max_length=255),
        ),
    ]
