# Generated by Django 4.2.3 on 2024-09-04 09:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_logs_date_alter_logs_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='date',
        ),
        migrations.RemoveField(
            model_name='logs',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='logs',
            name='start_time',
        ),
        migrations.AddField(
            model_name='logs',
            name='end_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logs',
            name='start_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
