# Generated by Django 4.2.3 on 2024-09-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_logs_date_remove_logs_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screencaptures',
            name='key_and_mouse_press',
            field=models.JSONField(default=dict),
        ),
    ]
