# Generated by Django 4.2.3 on 2024-09-23 11:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_screencaptures_key_and_mouse_press'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screencaptures',
            name='key_and_mouse_press',
        ),
        migrations.CreateModel(
            name='KeyMousePress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keyboardPress', models.CharField(max_length=255)),
                ('mouseClick', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('log_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_mouse_press', to='projects.logs')),
            ],
        ),
    ]
