# Generated by Django 4.2.3 on 2024-09-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_screencaptures_key_and_mouse_press_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='key_and_mouse_press',
            field=models.ManyToManyField(related_name='logs', to='projects.keymousepress'),
        ),
    ]
