# Generated by Django 4.2.3 on 2024-09-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_logs_key_and_mouse_press'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keymousepress',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
